### ISSUE TITLE
As a USER or VISITOR, I want an always-visible search bar on the home page

### ISSUE THREAD

**Issue by vhoof** [the-difference-engine/rescue-leftover-cuisine2#110]
The main search bar should be properly rendered when it is displayed:
- [ ] Darkened/muted background image
- [ ] Drop shadow on the search bar
- [ ] Magnifying glass on right
- [ ] Placeholder text

When the user scrolls up so that the search banner is not displayed, a search bar appears in the header:
- [ ] Grey-ish background (from design)
- [ ] Magnifying glass on left
- [ ] Placeholder text

When the main search banner scrolls back into view, the search bar in the header disappears.

**Comment by tkhutch** [comment]
@ryandwalters I was speaking with @mglavey and it sounds like a lot of this is done except for some styling. Can she pull your changes for review and/or help you finish this one up?
