### ISSUE TITLE
Create the Create Recipe page

### ISSUE THREAD

**Issue by mglavey** [the-difference-engine/rescue-leftover-cuisine2#111]
Front-End Only: Create the recipe form as outlined in the design document.

![image.png](https://images.zenhubusercontent.com/5c2ea74fa3ed691d821afa37/35da4bea-49fe-446d-bef9-24c5f6c51d62)

**Comment by mglavey** [comment]
[ ] Change text areas to input fields.
[ ] Change icons to Icon8 to match recipe card.
[ ] Change dropdown to select (and change color from grey to white).
[ ] Tags input box functionality.
[ ] Drag and drop feature for ingredients and directions list.
[ ] Base64 for photo uploading and frontend storage.

**Comment by mglavey** [comment]
[  ] Change text areas to input fields.
[  ] Change icons to Icon8 to match recipe card.
[  ] Change dropdown to select (and change color from grey to white).
[  ] Tags input box functionality.
[  ] Drag and drop feature for ingredients and directions list.
[  ] Base64 for photo uploading and frontend storage.

**Comment by tkhutch** [comment]
@evi-tde Here's the ticket you can break down.
