### ISSUE TITLE
Recreate recipe model in backend

### ISSUE THREAD

**Issue by vhoof** [the-difference-engine/rescue-leftover-cuisine2#118]

**Comment by mareann** [comment]
What is meal field for?
I have the scripts ready for recipe and tags except for timestamp and many relationships
Will work on that...
My branch is RecipeSeedsUpdate

**Comment by vhoof** [comment]
Meal is for which meal it is (breakfast, lunch, dinner, snack). I think we could use tags, but this one seems to have a special significance.
