### ISSUE TITLE
Fix history in frontend

### ISSUE THREAD

**Issue by vhoof** [the-difference-engine/rescue-leftover-cuisine2#119]
Remove history.js and use `this.props.history` or similar from router.

**Comment by vhoof** [comment]
We'll want to remove the `history.js` file and all the places it's imported. Instead, we'll want to make use of the history functionality from react-router-dom.

It's quite possible that `this.props.history` will be available on the pages that are routed to, and will have to be threaded through to sub-components where necessary.

If not, we can make use of `withRouter` to provide the history to any component that needs it.

**Comment by KatieLars** [comment]
I didn't see a lot of places where history was imported; just App.js. And I didn't see any pushes to history or any mention of it on the API end . . . was there something I missed?

After some reading, I also decided just to import `withRouter` into App.js and just wrap it around this component when exporting it. Theoretically everything should have access to history, although we may need to deconstruct the props to get it. 

But I'm not sure if this will work as I'm not seeing history actually being used.
