### ISSUE TITLE
Create recipe list and detail endpoints

### ISSUE THREAD

**Issue by vhoof** [the-difference-engine/rescue-leftover-cuisine2#120]
We want a new rails controller:

`GET /api/v1/recipe`

Returns a list of recipes.

`GET /api/v1/recipe/:recipe_id`

Returns the details about a single recipe.

**Comment by tkhutch** [comment]
@mglavey  This is a subset of #6.

**Comment by vhoof** [comment]
Evan's branch `search-db` already has a good start on these endpoints, but we'll probably want to modify the `show` method, at least, to handle missing items.
