### ISSUE TITLE
Create schema/model for recipes

### ISSUE THREAD

**Issue by BoVice** [the-difference-engine/rescue-leftover-cuisine2#14]
Create initial schema and model for recipes.

https://docs.google.com/spreadsheets/d/1_fmmmjKUSvq6jiwD5KjcOEHeOUxe_fZGtjUlD1l0FPg/edit#gid=0

Recipe Title | Recipe Description | Ingredients | Directions | Difficulty | Duration | Servings | Tag1 | Tag2 | Tag3 | Photos | Comments

**Comment by BoVice** [comment]
@matthewschoen25 Could you add some info here on what attributes are required for a recipe?

**Comment by matthewschoen25** [comment]
Recipes data file:

https://docs.google.com/spreadsheets/d/1_fmmmjKUSvq6jiwD5KjcOEHeOUxe_fZGtjUlD1l0FPg/edit#gid=0

**Comment by matthewschoen25** [comment]
![image](https://user-images.githubusercontent.com/41599308/43431872-b89e377c-9435-11e8-826b-0497739c98d1.png)
