### ISSUE TITLE
Create boilerplate CSS for UI styleguide

### ISSUE THREAD

**Issue by BoVice** [the-difference-engine/rescue-leftover-cuisine2#15]
We will be using [PostCSS](https://github.com/postcss/postcss) as our css preprocessor. The style guide can be found here https://drive.google.com/open?id=1rE9Lfx1xCkda7ay5u4vm4u9H61MkAM5D

**Comment by ADFrys** [comment]
Add var postcss = require("postcss"); to application.js file under frontend/packs
Next step to create variables for each UI color. Documentation can be found here:
http://api.postcss.org/AtRule.html#append

**Comment by ryandwalters** [comment]
There are custom icons under iconography on the style guide that we would like to request from the design team.![icongraphy.jpg](https://images.zenhubusercontent.com/5a870c784b5806bc2bc73a4e/5a53272a-7218-4a1f-854f-ab3691989d64)
