### ISSUE TITLE
As a VISITOR, I want to be able to sign up for an account so that I can take advantage of USER features

### ISSUE THREAD

**Issue by tkhutch** [the-difference-engine/rescue-leftover-cuisine2#156]
Acceptance Criteria
- [ ] I can enter text into the First Name, Last Name, Email, and Password fields on the signup/login page
- [ ] The email field validates that I have entered an email in a valid format
- [ ] The Sign Up button is greyed out until all fields are completed
- [ ] When I click the signup button, my user data is inserted into the user table. My user type should be "user"
 - [ ] If the account is successfully created, a success message component (see image and design doc) is displayed on the page. Otherwise, an error message is displayed.

Success Message Component
![image.png](https://images.zenhubusercontent.com/5c2ea74fa3ed691d821afa37/fa15952a-864c-45d5-a893-1534a337ccae)

Out of scope
- Sending an email for verification (#34)
- Password complexity requirements/feedback

**Comment by vhoof** [comment]
Here's what the API looks like:

`POST /api/v1/user` to signup

This expects a user object containing fields:
```json
{
    "user": {
        "email": "email@email.com",
        "password": "password",
        "first_name": "John",
        "last_name": "Doe"
    }
}
```

In case of missing or bad fields, the endpoint will return a `422 Unprocessable Entity`. The body will contain an errors object describing the problems:

```json
{
    "errors": {
        "email": [
            "can't be blank"
        ],
        "password": [
            "can't be blank"
        ]
    }
}
```

On success, the endpoint will return a 201 (Created). If the user's email is already taken by another user, the endpoint will return a 409 (Conflict).
