### ISSUE TITLE
Create a partial for forms

### ISSUE THREAD

**Issue by BoVice** [the-difference-engine/rescue-leftover-cuisine2#16]
Please see go to the following link to download the mockups and styleguides to refence how forms should look like. https://drive.google.com/drive/u/1/folders/1ZoTvyRT8yfko4yT7W0HRCguWUzucbsD2

**Comment by JennaDalgety** [comment]
If I'm understanding this correctly, this should just be a basic form mock-up?  Should I build templates to be used, like a new recipe form, and log in form, for example?

Also, we're using React for the front-end, yes?   There's a node module called React Bootstrap.  Should we consider using this module? https://react-bootstrap.github.io/

**Comment by matthewschoen25** [comment]
Recipe Form:  There are 3 recipe forms: recipes from search, recipes from suggestions,  and my recipes:

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/0e04725a-fcbe-47c4-8834-174a4f9cf86f)

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/12f1b56c-a9d6-4b07-b4b3-7d35780e9351)

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/2178a24b-f755-489a-b0cf-8e01e7952c6e)

Recipe Creation form:

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/8734e869-beda-4277-b692-c62889b891f1)

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/f5ca6bd7-fec7-44e1-acdb-3dee39c67e2f)

Ingredients and Directions form:  ADD data form 
![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/dfe2eec1-6b5c-4360-9fdd-cda9c6da78c2)

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/ef441b95-6d4c-
40a9-9ceb-bb50e050bb4f)

admin form: manage recipes and manage users form (members updates form) are the same:

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/e9280ecd-f45e-4ff3-9786-79f737db275e)

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/21469927-4949-4c97-8b33-1919baa645dd)
