### ISSUE TITLE
Build the Login Page

### ISSUE THREAD

**Issue by tkhutch** [the-difference-engine/rescue-leftover-cuisine2#160]
Build the login page as outlined in the design document.

![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/125a9148-c7b8-44a0-acb7-6d243b7cc09f)

**Comment by tkhutch** [comment]
@vhoof Can you add the link to the branch with Evan's code?

**Comment by vhoof** [comment]
https://github.com/the-difference-engine/rescue-leftover-cuisine2/tree/login-age

**Comment by tkhutch** [comment]
@KatieLars Here's a photo we can use for the backdrop of the login page. Thinking we can crop some of the wood off the top in order to make it the right dimensions: https://www.pexels.com/photo/basil-delicious-food-ingredients-459469/
