### ISSUE TITLE
Create AWS free tier account

### ISSUE THREAD

**Issue by tkhutch** [the-difference-engine/rescue-leftover-cuisine2#188]
We will use S3 for storage, so we need an AWS account. The client has one but does not want to share credentials until closer to project completion, so we will create a free tier account to use for now.

**Comment by tkhutch** [comment]
@vhoof Per what we discussed, if you can create this off of your Heroku account, that would be great.

**Comment by vhoof** [comment]
I've created two buckets:

`tde-rlc-images-stg`
`tde-rlc-images-prod`

I've also created an IAM user with access to these buckets, and placed the credentials on the staging and production heroku apps.
