### ISSUE TITLE
Add fixed position Navigation Bar on header.  

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#23]
Different functionality within navigation bar depending on user type (Visitor, admin, user)
user has a profile and login functionality

**Comment by EvanGrillo** [comment]
navbar component to work with devise 

Objectives: 

!Authorized -
Login/Signup

else
Logout/Edit User Profile

**Comment by ryandwalters** [comment]
Fixed position navbar react and html for homepage view.
