### ISSUE TITLE
To Fix: Validation on email field of signup form only checks for @ symbol, not period in domain

### ISSUE THREAD

**Issue by tkhutch** [the-difference-engine/rescue-leftover-cuisine2#242]
On /login, the signup form has validation logic if an email in the wrong format is entered and then the sign up button is pressed.

Currently, entering something like "test" or "test@" will trigger the validation message, but "test@no" will not.

Update the validation logic to enforce that the email is in the format "something@something.something". In other words, check that there is a "." somewhere after the @ symbol.

If there is not, display the error message: "There must be a . in the email address after the @ symbol."

**Comment by andreaMT15** [comment]
@SamDesai333 Can you please do a code review for this ticket?
