### ISSUE TITLE
To Fix: Styling on page indicator on the Admin dashboard

### ISSUE THREAD

**Issue by tkhutch** [the-difference-engine/rescue-leftover-cuisine2#293]
Currently in app:

![image.png](https://images.zenhubusercontent.com/5c2ea74fa3ed691d821afa37/5c619507-dc70-4f44-ae67-e82e3090b12c)

Desired Styling:

![image.png](https://images.zenhubusercontent.com/5c2ea74fa3ed691d821afa37/f2ca3815-908d-4c1f-9f0e-78ff449f2043)

So that the number doesn't look so odd, let's keep the < and > on either sides of the list of pages but make them not hyperlinks when there aren't actually more results

**Comment by sbudisav** [comment]
I got the pagination arrows working pretty easy. They are colored (blue) when there are more pages available to click, and black and un-clickable when there are no more pages. 

Functionality is fine but the styling is still boxed. I'm going to go hunting around for a styling that matches the picture shown in the ticket. 
<img width="209" alt="Screen Shot 2019-07-24 at 7 22 31 PM" src="https://user-images.githubusercontent.com/32229605/61837112-e981ff80-ae48-11e9-80f0-a3a4ecff0a14.png">
