### ISSUE TITLE
As a User, I want to securely reset my password from within the app so that I can follow good security practices

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#31]
On the user settings page, there is a form for the user to change their password. This ticket implements the functionality that actually allows the user to change their password.

Acceptance criteria:
- [ ] Entering a sufficiently complex password and two entries that match will change the user's password in the database
- [ ] Entering an insufficiently complex password will display an error and not change the user's password
- [ ] Entering a password and a confirm that do not match will display an error and not change the user's password
- [ ] Entering a password that is the same as the current (previous) password will display an error, not log the user in, and not change the user's password.
- [ ] Password reset links will expire after 24 hours and after the password is successfully reset
- [ ] The "show password" images appear in the password field and clicking them reveals the user's password

**Comment by EvanGrillo** [comment]
User will see password message on password rules after failing to meet criteria

**Comment by EvanGrillo** [comment]
UI requests + tracking password history to revisit after MVP is complete

**Comment by tkhutch** [comment]
Front end was created via #165
