### ISSUE TITLE
Recipes should take their meal designation from tags

### ISSUE THREAD

**Issue by vhoof** [the-difference-engine/rescue-leftover-cuisine2#381]
In displaying the green meal tag on the recipe card (and the meal on the recipe page), we should search for particular tags labeling the meal instead of using the meal parameter. If a recipe has multiple meal tags, pick one for the green meal tag based on the following priority:

Dinner
Breakfast
Lunch
Snack

**Comment by tkhutch** [comment]
@vhoof I'm going to move this to icebox for now and reword. Rather than build this logic, we're just going to remove that green lozenge entirely since this is something the designer came up with and it's not in the scoping notes anywhere as a requirement.
