### ISSUE TITLE
As an ADMIN, I want to be able to Create and Read (CRUD)

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#4]
** Admin **
- [ ] As an ADMIN, I want to be able to Create and Read new user accounts 

- [ ] Create DB new user table (see ticket #8) or (Ticket #16) Forms
- [ ] Populate table with a few sample data
- [ ] Create select DB script
- [ ] Create for user viewing information
- [ ] Create admin dashboard which includes (user name, email, membership date, number of recipes) See comments and HF pictures

**Comment by tomlouismurphy** [comment]
this ticket is currently complete except for writing the relevant rspec tests. I expect to finalize the pull request Tuesday 8/28
