### ISSUE TITLE
As a visitor, I want to click on the landing page sign up button so that I am directed to a new page to create an account.  (See attached photo)

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#52]
![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/125a9148-c7b8-44a0-acb7-6d243b7cc09f)

Acceptance crieteria:

- [ ] Clicking on the Log In or Sign Up button at the top of the page directs the user to the login page
- [ ] Clicking on the Sign Up button towards the bottom of the page (see screenshot) directs the user to the login page

![image.png](https://images.zenhubusercontent.com/5c2ea74fa3ed691d821afa37/b9fab1af-752f-4235-990b-52e3d9e950cb)

**Comment by EvanGrillo** [comment]
First draft:

**Comment by tkhutch** [comment]
@EvanGrillo I've edited this to reflect the fact that we only need the create an account piece for now.

**Comment by tkhutch** [comment]
Added some requirements from an overlapping ticket.

**Comment by tkhutch** [comment]
@guitarlanguage The button and the login page both exist. So this card is just linking the button to the login page so that when the button is clicked, it takes the user to the login page.

**Comment by tkhutch** [comment]
@guitarlanguage I updated this ticket slightly today, as there are two places the homepage needs to link to the login/signup page: at the top and then also further down on the page. Wanted to give you a heads up.
