### ISSUE TITLE
As an Admin, I would like to be able to view all recipes in the dashboard so that I know what users have submitted

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#60]
Acceptance criteria

[ ] All recipes in the database are returned in the dashboard
[ ] The default sort is by submitted date, from newest to oldest
[ ] 20 recipes are shown per page
[ ] The guide at the bottom shows the total number of pages based on the query. (Note that you may need to do something along the lines of "< 1, 2, 3, 4, 5, 6, 7, 8... 20 >" for longer results)
[ ] Clicking the arrow on the page guide moves you forward or back among the pages. Clicking a number jumps to that specific page
[ ] Each entry in the database is shown only once
[ ] There are no character encoding or other data display issues

**Comment by tkhutch** [comment]
@vhoof - This is a legit ticket that's in this sprint. I repurposed one Matt had in.
