### ISSUE TITLE
Research social media sharing

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#7]
Research how to add sharing buttons for:
- Twitter
- Instagram
- Pinterest
- Facebook

Please create a page on the GitHub wiki to document findings and link to the developer docs for these sites.

**Comment by tkhutch** [comment]
@jsmith2890 As we discussed today, please start researching how we would do this for Facebook, Instagram, Pinterest, and Twitter.
