### ISSUE TITLE
Add Figaro gem to handle environment variables

### ISSUE THREAD

**Issue by zachgarwood** [the-difference-engine/rescue-leftover-cuisine2#72]
Figaro: https://github.com/laserlemon/figaro

After you get the gem installed and configured, please change [this line](https://github.com/the-difference-engine/rescue-leftover-cuisine2/pull/54/files/a8e0700a2c3efb86247b28d97f885c663a127c73#diff-a8a4112d0760c0fd11f691c6a5fb22adR11) back to the original, ie.:
```ruby
config.secret_key = ENV["SECRET_DEVISE_KEY"]
```

**Comment by EvanGrillo** [comment]
Updated on environment variables via Figaro: https://github.com/the-difference-engine/rescue-leftover-cuisine2/wiki/Mailer-&-Environment-Variables-for-Development
