### ISSUE TITLE
As a USER/VISTOR, I would like to sign into my account, so that I can use the website

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#8]
Acceptance Criteria: 

- [ ] I can enter my username and password into the login form
- [ ] The login button is greyed out/disabled until I enter both username and password
- [ ] Password is obscured (i.e. dots instead of actual characters entered)
- [ ] If my username and password are correct, upon clicking the login button, I am logged into the application with a valid session
- [ ] If my username and/or password are incorrect, a message letting me know that is displayed on the page after clicking the Log In button

Notes:
Please see the attached screen shots and visit the RLC_HF_v10_final

 https://drive.google.com/drive/u/1/folders/1ZoTvyRT8yfko4yT7W0HRCguWUzucbsD2

**Comment by matthewschoen25** [comment]
![image](https://user-images.githubusercontent.com/41599308/43556350-f4b1deea-95c4-11e8-852a-97b99582fe0d.png)

**Comment by matthewschoen25** [comment]
![image](https://user-images.githubusercontent.com/41599308/43556390-2a6aaf08-95c5-11e8-89c8-5bd5c0c02765.png)

**Comment by matthewschoen25** [comment]
![image](https://user-images.githubusercontent.com/41599308/43556402-4479a548-95c5-11e8-80fe-a8cd25aa79ee.png)

**Comment by matthewschoen25** [comment]
![image](https://user-images.githubusercontent.com/41599308/43556426-5f0db2e6-95c5-11e8-8f75-611ed280be28.png)

**Comment by matthewschoen25** [comment]
![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/906c7b97-ba11-4fce-b3b8-2afead5f265d)

**Comment by matthewschoen25** [comment]
![image.png](https://images.zenhubusercontent.com/5b566e484b5806bc2bdcac5e/e50618da-ff72-4aa6-9f7f-b5995d74647e)

**Comment by EvanGrillo** [comment]
![Screen Shot 2018-08-08 at 7.33.43 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/f5d85cf8-f901-4bdc-ab76-86cbc142c84a)
![Screen Shot 2018-08-08 at 7.37.19 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/5464c5b4-00d7-4f27-881d-730da66cd2ef)
![Screen Shot 2018-08-08 at 7.37.10 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/e1501e50-3b98-4ecc-a9d2-bdec36e81cfd)
![Screen Shot 2018-08-08 at 7.36.36 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/59b88492-55a7-4144-a181-3b8cc3084221)
![Screen Shot 2018-08-08 at 7.34.46 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/4461d249-a646-4f68-af29-49d700bda0f0)
![Screen Shot 2018-08-08 at 7.34.36 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/859af34c-100f-4a86-a985-21d0239f8759)
![Screen Shot 2018-08-08 at 7.37.30 PM.png](https://images.zenhubusercontent.com/5b567ed8a23d3d1b2eb8096e/76d48a84-0a0e-4a7a-a76f-436066ffc273)

**Comment by tkhutch** [comment]
This will be the ticket to handle login after the user registers.

**Comment by vhoof** [comment]
Here's what the API looks like:

`POST /api/v1/auth/login` to login

This also expects a user object, but only containing login details:
```json
{
    "user": {
        "email": "email@email.com",
        "password": "password"
    }
}
```

Given missing fields or a bad user/password combo, the endpoint will return a `401 Unauthorized` status and a JSON object describing the failure:

```json
{
    "errors": [
        {
            "title": "Unauthorized",
            "message": "Invalid Email or password."
        }
    ]
}
```

If successful, the endpoint will return a 200 or a 201. It will also contain an `Authorization` header, which will contain a bearer token. We'll want to save that and put it in local storage, as that will be how we authenticate future requests to the API.
