### ISSUE TITLE
Create tile for recipes within search results

### ISSUE THREAD

**Issue by matthewschoen25** [the-difference-engine/rescue-leftover-cuisine2#80]
Create the recipe tile that will be iterated in the search results page.

See front end recipe views:  

https://drive.google.com/drive/folders/1ENDnDsgZPN_iE6VaYlayiR9JsPzybbbq?usp=sharing

See the view labeled "Landing Page" for an example of how the tiles should look.

**Comment by tkhutch** [comment]
@EvanGrillo I've edited this to be only creating the landing page view, as that's what will be relevant for the next demo. This may overlap with working being done by @mglavey and @mareann on the basic site, so please discuss on Monday.

**Comment by tkhutch** [comment]
Further edited to be only the tile.
