### ISSUE TITLE
Build skeleton of home page

### ISSUE THREAD

**Issue by zachgarwood** [the-difference-engine/rescue-leftover-cuisine2#88]

**Comment by zachgarwood** [comment]
Create a basic skeleton of how the home page will look. You can create dummy components as placeholders for components we don't have yet.

**Comment by tkhutch** [comment]
@mglavey I'm adding you to this card, as I understand it relates to what you're doing with the other card you created.

**Comment by vhoof** [comment]
We'll want at least the header, the main search, the recipe list, the bottom signup bit, and the footer.
